apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-carrier
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-carrier
  chart:
    git: ssh://git@github.com/Param-ACN/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net.fab.cluster31.aws.bafevent.com:8443
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a06cfdd75c77e11ea9b010a5d49687c5-985557784.ap-south-1.elb.amazonaws.com:9000
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.fab.cluster31.aws.bafevent.com:8443
    anchorstx: |-
      Cr0CChAKDggCIgphbGxjaGFubmVsEqgCCqUCCgphbGxjaGFubmVsEloSWAoLQXBwbGljYXRpb24S
      SQgBEj0KCmNhcnJpZXJNU1ASLxoHCgNNU1ASACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIAIgoK
      BkFkbWlucxIAKgZBZG1pbnMaugEStwEKC0FwcGxpY2F0aW9uEqcBCAESmgEKCmNhcnJpZXJNU1AS
      iwEIARpQCgtBbmNob3JQZWVycxJBEjcKNQowcGVlcjAuY2Fycmllci1uZXQuZmFiLmNsdXN0ZXIz
      MS5hd3MuYmFmZXZlbnQuY29tEPtBGgZBZG1pbnMaBwoDTVNQEgAiCwoHUmVhZGVycxIAIgsKB1dy
      aXRlcnMSACIKCgZBZG1pbnMSACoGQWRtaW5zKgZBZG1pbnM=

