apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: store-net-ca
  namespace: store-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: store-net-ca
  chart:
    git: ssh://git@github.com/Param-ACN/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: store-net
      images:
        alpineutils: https://hub.docker.com/repository/docker/ajaxav/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.4
    server:
      name: ca
      tlsstatus: true
      admin: store-admin
    storage:
      storageclassname: storesc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://a06cfdd75c77e11ea9b010a5d49687c5-985557784.ap-south-1.elb.amazonaws.com:9000
      authpath: store-net-auth
      secretcert: secret/crypto/peerOrganizations/store-net/ca?ca.store-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/store-net/ca?store-net-CA.key
      secretadminpass: secret/credentials/store-net/ca/store?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
